[project]
name = "api"
version = "0.4.1"
requires-python = ">=3.11,<4.0"
dependencies = [
  "fastapi>=0.115.8",
  "uvicorn>=0.34.0",
  "pydantic-settings>=2.8.0",
  "redis>=6.4.0",
  "isochrones @ git+https://github.com/EPFL-ENAC/isochrones.git@v0.5.1",
  "extractosm @ git+https://github.com/EPFL-ENAC/extractosm.git@v0.1.3",
  "typo-modal @ git+ssh://git@github.com/EPFL-LASUR/mobility-toolkit.git@v0.3.2",
]
description = "LASUR Web Services"
authors = [{ name = "Yannick Marcon", email = "yannick.marcon@epfl.ch" }]
license = { text = "GPLv3" }
readme = "README.md"

[dependency-groups]
dev = [
  "pytest>=8.3.4",
]

[tool.uv.build-backend]
module-name = "api"
module-root = ""
namespace = true

[build-system]
requires = ["uv_build>=0.12.6,<0.13"]
build-backend = "uv_build"
